AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Http Status
    
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
    Function:
        Timeout: 3


Resources:

    HttpStatusFunction:
        Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
        Properties:
            CodeUri: ./src
            Handler: app.lambdaHandler
            Runtime: nodejs8.10
            Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
                Variables:
                    PARAM1: VALUE
            Events:
                HttpStatus:
                    Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
                    Properties:
                        Path: /command
                        Method: post

Outputs:

    HttpStatusApi:
      Description: "API Gateway endpoint URL for Prod stage for Http Status function"
      Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/httpstatus/"

    HttpStatusFunction:
      Description: "Http Status Lambda Function ARN"
      Value: !GetAtt HttpStatusFunction.Arn

    HttpStatusFunctionIamRole:
      Description: "Implicit IAM Role created for Http Status function"
      Value: !GetAtt HttpStatusFunctionIamRole.Arn
